import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { getSession, signIn } from 'next-auth/react'

import logoImg from '../assets/logo.svg'

export default function Login() {
  return (
    <>
      <Head>
        <title>NLW COPA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="max-w-[640px] h-screen px-6 flex flex-col mx-auto items-center justify-center">
          <Image src={logoImg} alt="NLW Copa" />

          <h1 className="mt-14 text-white text-5xl font-bold leading-tight text-center">
            Crie seu próprio bolão da copa e compartilhe entre amigos!
          </h1>


            <button
              className="px-6 py-4 my-6 w-[100%] max-w-[640px] rounded bg-yellow-500 text-gray-900 font-bold text-sm uppercase hover:bg-yellow-700"
              type='button'
              onClick={() => signIn('google')}
            >
              Login com o Google
            </button>

          <p className="mt-4 text-sm text-gray-300 leading-relaxed">
            Após fazer seu login social, você poderá criar bolões 🚀
          </p>
        </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context)

  if(session) {
    return {
      redirect: {
        destination: '/',
        permanent: false
      }
    }
  }
  return {
    props: {
      session
    }
  }
}